version: 2
mergeable:
  - when: schedule.repository
    name: Stale pull request comment
    validate:
      - do: stale
        days: 30
        type: pull_request
        time_zone: Asia/Karachi
    pass:
      - do: comment
        payload: This is a stale pull request. Closing in 7 days.
    error:
      - do: comment
        payload: An error occured

  - when: schedule.repository
    name: Stale pull request close
    validate:
      - do: stake
        days: 37
        type: pull_request
    pass:
      - do: close
    error:
      - do: comment
        payload: An error occured

  - when: pull_request.*
    name: Commit message validator
    validate:
      - do: commit
        message:
          regex: ^\w+-\d
    pass:
      - do: labels
        add: "ReadyToMerge"
    fail:
      - do: labels
        add: "UnableToMerge"
      - do: comment
        payload: All commit message must contain Jira ticket ID
      - do: close
    error:
      - do: comment
        payload: An error occured
