version: 2
mergeable:
  - when: schedule.repository
    name: Stale pull request comment
    validate:
      - do: stale
        days: 30
        type: pull_request
        time_zone: Asia/Karachi
    pass:
      - do: comment
        payload:
          body: This is a stale pull request. Closing in 7 days.

  - when: schedule.repository
    name: Stale pull request close
    validate:
      - do: stale
        days: 37
        type: pull_request
    pass:
      - do: close

  - when: pull_request.*
    name: Commit message validator
    validate:
      - do: commit
        message:
          regex: ^\w+-\d+
    pass:
      - do: labels
        add: "ReadyToMerge"
    fail:
      - do: labels
        add: "UnableToMerge"
      - do: comment
        payload:
          body: All commit message must contain Jira ticket ID
      - do: close

  - when: pull_request.*
    name: Pull request description validator
    validate:
      - do: description
        no_empty:
          enabled: true
