name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        stale-issue-label: 'no-issue-activity'
        stale-issue-message: 'Stale issue message'

        stale-pr-label: 'no-pr-activity'
        stale-pr-message: 'Stale pull request message'
